blank_issues_enabled: false
contact_links:
    - name: ðŸ¤” Questions & General Discussion
      url: https://github.com/RanitManik/foody/discussions
      about: Please ask questions and participate in discussions for Foody
